import { useEffect } from 'react'
import { Link } from 'react-router-dom'
import { ArrowLeft, ArrowRight, Mail, ShieldCheck, Sparkles, Wrench } from 'lucide-react'

const pageContent: Record<string, { kicker: string; title: string; intro: string; sections: [string, string][] }> = {
  privacy: {
    kicker: 'YOUR PRIVACY', title: 'Privacy Policy', intro: 'This policy describes what the All in One PDF Tools application does with account data, document text, analytics and advertising. The site operator should review and update it for the laws and vendors that apply to their deployment.', sections: [
      ['PDF files and browser processing', 'Merge, split, rotate, extract pages, image conversion, text extraction, basic PDF overlays, signatures, watermarks, metadata updates and browser PDF creation run in your browser. The application does not upload the source document for those operations. A result is prepared locally and downloaded by you. Browser memory is temporary; closing the tab releases the application’s references, but you should also clear any downloaded files you no longer need.'],
      ['AI processing', 'AI features are optional. For Ask AI and study tools, selectable text is extracted locally in your browser and then sent to this site’s API. The API calls Google Gemini using a server-side secret; the key is never placed in frontend code. For AI document creation, your prompt and any details you enter are sent to the API and Gemini. Do not submit confidential, regulated, health, financial, or highly personal information unless you have permission and have reviewed the operator’s Gemini configuration and Google’s terms. The application does not intentionally store document text, prompts or generated content in its database.'],
      ['Accounts and history', 'If account services are configured and you register, we store your email address, a securely hashed password, optional display name, account status and session data. Processing history stores the tool used, filename, status and timestamp; it does not store the original PDF or extracted text. You can remove individual history entries or clear your history in your workspace. Password reset and account deletion workflows must be configured by the site operator before launch.'],
      ['OCR and external assets', 'OCR is performed in the browser with Tesseract.js. The OCR engine and language data may be fetched from the configured public package and language-data hosts when you first use OCR. The PDF pages are passed to the OCR worker in the browser; the application does not upload the PDF to an OCR API. Review your deployment Content Security Policy and package versions before enabling OCR in production.'],
      ['Analytics and consent', 'Optional analytics are disabled until you choose “Analytics only” or “Allow all.” If enabled, the browser sends page-view and tool-use events to the site backend. The backend derives a pseudonymous visitor identifier from the connecting IP and a server secret that rotates by calendar month; it does not store the raw IP. Daily counts group the current day’s events, while monthly counts can deduplicate across days within that month. It may record page path, tool identifier, country inferred by the edge network, broad device type and browser family. Analytics events are retained for up to 13 months in the provided Worker cleanup job. Advertising consent is separate; enabling analytics does not load ad scripts. You can change either choice using “Privacy choices” in the footer.'],
      ['Advertising', 'The supplied publisher tags create a 728×90 banner on the home page and at the top of tool pages, plus a native placement below the tool work area. No advertising script is injected until you choose “Ads only” or “Allow all”; existing visitors without an advertising choice are prompted. The banner tag loads from highrevenueformat.com and the native tag from profitableratecpmnetwork.com. If allowed, these third-party scripts run in the page and may receive request, device/browser and page/referrer data or use their own storage under their policies. The tool does not intentionally attach selected PDF bytes to ad requests, but third-party scripts should be treated as code with access to the page. Review the providers and applicable laws before launch. Ads are clearly labelled and are not download or processing controls.'],
      ['Temporary storage and retention', 'As currently configured, document conversion is unavailable and conversion uploads are rejected before a file is stored. If the operator enables a genuine conversion provider, only the document explicitly submitted for that asynchronous job is temporarily stored in a private location (R2 on Cloudflare or a non-public server directory on cPanel) and sent to that provider. The source is deleted after completion or failure. A completed result is deleted two minutes after its download stream finishes; if it is never downloaded, it expires after one hour by default (the operator may configure a longer 1–24 hour window). A durable cleanup queue and periodic expiry cleanup provide safeguards. Review the provider contract and this policy before uploading sensitive material. Browser-based PDF tools continue to run locally. The server cannot erase a copy already downloaded to your device.'],
      ['Security and your choices', 'The Worker includes HTTPS-oriented security headers, same-origin checks for state-changing requests, rate limiting, HttpOnly secure sessions, input validation and PBKDF2 password hashing. No internet service can guarantee absolute security. You may use local browser tools without an account; AI, account features and consent-based analytics are optional.'],
      ['Contact and changes', 'The deployed operator should publish a monitored contact address and a data-protection contact where required. Replace this placeholder policy with a reviewed policy that identifies the controller, jurisdiction, retention schedule, subprocessors and user-rights process before commercial launch.'],
    ]
  },
  terms: {
    kicker: 'THE GROUND RULES', title: 'Terms of Service', intro: 'These starter terms describe responsible use of this application. The site operator should obtain legal review and adapt them to the business, jurisdiction and services actually deployed.', sections: [
      ['Use of the application', 'You may use available tools for lawful work with documents you own or are authorized to process. Do not use the service to violate another person’s rights, distribute malware, evade access controls, or process material unlawfully. You are responsible for reviewing the output and retaining an original copy where appropriate.'],
      ['Tool availability and conversion', 'Capabilities vary by tool and deployment. The interface identifies service-dependent conversions that are not configured. The site does not claim that an unavailable conversion, password operation or redaction has been performed. Features may change or become unavailable.'],
      ['AI-generated content', 'AI output can be incomplete, inaccurate, biased or misleading. It is a draft for human review, not legal, medical, financial, employment or other professional advice. Verify facts, references, names, dates and figures against reliable sources. You are responsible for how generated content is used.'],
      ['Electronic signature and security tools', 'A signature image placed by this application is an electronic mark; it is not automatically a qualified digital signature, identity verification, government certification or cryptographic certificate. Password protection, password removal and secure redaction are not enabled in this deployment. Do not rely on an unavailable security feature.'],
      ['Accounts and acceptable use', 'If accounts are enabled, provide accurate registration information and keep your credentials confidential. The operator may limit or suspend accounts used to abuse the application, exceed reasonable limits, or compromise its security. Account recovery and deletion options must be supplied by the operator.'],
      ['No warranty; limitation', 'The application is provided on an “as available” basis to the maximum extent allowed by law. The operator does not warrant that a tool will meet a particular requirement or that a converted file will preserve every layout detail. Nothing in these terms excludes rights that cannot legally be excluded. The final deployed terms require legal review.'],
    ]
  },
  cookies: {
    kicker: 'SMALL DATA, CLEAR CHOICES', title: 'Cookie Policy', intro: 'This application uses a small number of browser storage features to remember your preferences and operate optional account sessions.', sections: [
      ['Essential local storage and consent', 'The theme preference and separate analytics and advertising choices are stored in local storage so your preferences persist. The keys are used to remember your selection; the core local PDF tools do not need an account cookie. Clear this site’s local storage or use your browser’s site-data controls to withdraw both choices; the site will prompt you again.'],
      ['Account session cookie', 'If accounts are configured, a session cookie named a1pt_session is marked HttpOnly, Secure and SameSite=Lax. It supports sign-in and is not used for cross-site advertising. It expires after seven days or when you sign out.'],
      ['Optional analytics', 'Analytics are off by default. Choose “Analytics only” or “Allow all” to enable consented usage events to the site backend. “Ads only” does not enable analytics. You can change your choices using “Privacy choices” in the footer or clear the site’s local storage.'],
      ['Advertising and third parties', 'The banner tag from highrevenueformat.com and the native ad tag from profitableratecpmnetwork.com are not loaded until you choose “Ads only” or “Allow all.” The banner appears at the top of the home page and tool pages; the native placement appears below the tool work area. When permitted, these third-party scripts may make network requests and use cookies or similar browser storage under their respective policies. Browser settings or extensions may block ads. Review the vendors’ policies and local consent requirements before use.'],
    ]
  },
  disclaimer: {
    kicker: 'PLEASE REVIEW', title: 'Disclaimer', intro: 'A practical reminder about document processing, conversions, signatures, redaction and AI output.', sections: [
      ['Document review', 'Always open and inspect a processed file before relying on or sharing it. Keep the source document until the result has been checked. Use of browser tools is subject to your device’s memory, browser behavior, PDF structure and file quality.'],
      ['AI output', 'AI-generated content is not guaranteed to be correct, complete, original, current or suitable for a particular purpose. Verify every consequential claim. AI summaries can omit qualifications, exceptions or context in the source document.'],
      ['Signatures', 'The signature feature creates an electronic signature image. It does not automatically create a qualified digital signature or government-certified signature, verify identity, provide a certificate, or guarantee that a recipient will accept the signature.'],
      ['Redaction and encryption', 'Secure redaction, password protection and unlocking are not enabled in this deployment. A black rectangle placed over text is not secure redaction. Do not rely on a visual cover-up to remove sensitive content.'],
      ['Conversions', 'PDF-to-Word, Office conversions and other conversions that require an external engine are disabled until a genuine conversion service is configured. No file is merely renamed to simulate conversion.'],
    ]
  },
  about: {
    kicker: 'ABOUT THE PROJECT', title: 'Documents deserve better tools.', intro: 'All in One PDF Tools is designed as a focused, privacy-conscious workspace for common PDF tasks—not a collection of upload forms disguised as utilities.', sections: [
      ['A practical toolkit', 'The application brings together browser-based page organization, image conversion, text extraction, simple overlays, metadata inspection, signatures, OCR and optional AI drafting. Every feature is identified honestly: some run locally, some require a backend, and unsupported conversions are clearly marked instead of faked.'],
      ['Private by design', 'For supported browser tools, the source file stays on your device. AI is a separate, opt-in workflow because document text has to reach the configured model provider. The account history is metadata-only and optional.'],
      ['Built to be deployed', 'The frontend is a React and TypeScript application. A Cloudflare Worker can serve the application and API, D1 stores account and analytics records, and Gemini is called only from the backend. A custom domain is configured at deployment rather than hardcoded into the app.'],
    ]
  },
  contact: {
    kicker: 'GET IN TOUCH', title: 'Contact', intro: 'Questions about the application or a privacy request should go to the service operator. Add a monitored contact address before publishing this site commercially.', sections: [
      ['Support', 'This codebase does not invent a support mailbox or collect contact messages. Configure your organization’s monitored support email and privacy contact in the production deployment, then update this page with the correct response times and escalation process.'],
      ['Document help', 'For a processing problem, include the tool name, browser, approximate file size and steps to reproduce. Do not email sensitive documents unless the operator has provided an approved secure channel and you are authorized to share them.'],
      ['Privacy requests', 'The operator should publish instructions for access, correction and deletion requests, including how account records and consented analytics events are handled.'],
    ]
  },
  'not-found': {
    kicker: 'PAGE NOT FOUND', title: 'That page isn’t here.', intro: 'The link may be out of date, or the page may have moved. Let’s get you back to a useful tool.', sections: []
  },
}

export default function InfoPage({ page }: { page: string }) {
  const content = pageContent[page] || pageContent['not-found']
  useEffect(() => {
    document.title = `${content.title} — All in One PDF Tools`
    const description = document.querySelector('meta[name="description"]')
    if (description) description.setAttribute('content', content.intro)
    const canonical = document.querySelector('link[rel="canonical"]') || document.createElement('link')
    canonical.setAttribute('rel', 'canonical')
    canonical.setAttribute('href', `${window.location.origin}${window.location.pathname}`)
    if (!canonical.parentNode) document.head.appendChild(canonical)
  }, [content.title, content.intro])
  return <section className="info-page"><div className="wrap"><div className="breadcrumb"><Link to="/">Home</Link><span>/</span><span>{content.title}</span></div><header className="info-header"><div className="info-icon">{page === 'privacy' ? <ShieldCheck size={22} /> : page === 'about' ? <Wrench size={22} /> : page === 'contact' ? <Mail size={22} /> : <Sparkles size={22} />}</div><span className="section-kicker">{content.kicker}</span><h1>{content.title}</h1><p>{content.intro}</p></header><div className="info-body">{content.sections.map(([title, body]) => <article key={title}><h2>{title}</h2><p>{body}</p></article>)}{page === 'not-found' && <Link to="/" className="button button-primary">Back to home <ArrowRight size={16} /></Link>}</div><div className="info-back"><Link to="/" className="text-link"><ArrowLeft size={15} /> Back to PDF tools</Link></div></div></section>
}
